info:
  # Root URL where the site will be published
  url:         http://incorporated.sendtoinc.com

  # Blog Information
  title:        "Cloudreach FR"
  subtitle:     "Not if. When"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Cloudreach
  company_url:  http://cloudreach.com/fr-fr/
  facebook:
  twitter:
  github:
  gplus:
  about_link:   https://cloudreach.com/fr-fr/

  # Product Information
  product_link: http://cloudreach.com/fr-fr/
  tagline:      "Not if. When"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

relative_permalinks:  true
paginate:             10
excerpt_separator:    "<!-- more -->"

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false